metrics-server:
  # this is a requirement for docker on MacOS
  args:
    - --kubelet-insecure-tls
  hostNetwork:
    enabled: false

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
