image: greegorey/ci:1.0.0

stages:
  - build
  - helm lint
  - prepare
  - deploy

# I don't use proper tags here, it's just for demo
# NOTE: push won't work because the lack of auth credentials
.build: &build
  script:
    - docker build -t $REPOSITORY:$TAG -f ./images/$DIR/Dockerfile ./images/$DIR
    - docker push $REPOSITORY:$TAG

build ci image:
  variables:
    DIR: ci
    REPOSITORY: greegorey/ci
    TAG: 1.0.0
  stage: build
  <<: *build

build load-test image:
  variables:
    DIR: load-test
    REPOSITORY: greegorey/load-test
    TAG: 1.0.0
  stage: build
  <<: *build

build wp image:
  variables:
    DIR: wordpress
    REPOSITORY: greegorey/wordpress
    TAG: 1.0.0
  stage: build
  <<: *build

helm lint:
  stage: helm lint
  script:
    - helm lint charts/*

# we use here secret Gitlab variables:
# - KUBECONFIG_B64
.k8s: &k8s
  before_script:
    - echo $KUBECONFIG_B64 | base64 --decode > ~/.kube/config

apply namespace:
  stage: prepare
  <<: *k8s
  script:
    - kubectl apply
      --filename ./manifests/namespace.yaml

# TODO:
# - kubectl rollout status --namespace kube-system statefulset/nfs --watch
deploy metrics-server:
  stage: prepare
  <<: *k8s
  script:
    - helm template
      --name nfs
      --namespace kube-system
      charts/metrics-server >
      templated.yaml
    - kubectl apply
      --namespace kube-system
      --filename templated.yaml

# TODO:
# - kubectl rollout status --namespace kube-system statefulset/nfs --watch
deploy nfs:
  stage: prepare
  <<: *k8s
  script:
    - helm template
      --name nfs
      --namespace kube-system
      charts/nfs-server-provisioner >
      templated.yaml
    - kubectl apply
      --namespace kube-system
      --filename templated.yaml

# we use here secret Gitlab variables:
# - ROOT_PASSWORD
# - REPLICATION_PASSWORD
#
# TODO:
# - kubectl rollout status --namespace wp statefulset/mariadb-master --watch
# - kubectl rollout status --namespace wp statefulset/mariadb-slave --watch
deploy db:
  stage: deploy
  <<: *k8s
  script:
    - helm template
      --name mariadb
      --namespace wp
      --set mariadb.rootUser.password=$ROOT_PASSWORD
      --set mariadb.db.password=$USER_PASSWORD
      --set mariadb.replication.password=$REPLICATION_PASSWORD
      charts/mariadb >
      templated.yaml
    - kubectl apply
      --namespace wp
      --filename templated.yaml

deploy wp:
  stage: deploy
  <<: *k8s
  script:
    - helm template
      --name wordpress
      --namespace wp
      --set db.password=$USER_PASSWORD
      charts/wordpress >
      templated.yaml
    - kubectl apply
      --namespace wp
      --filename templated.yaml
