mariadb:
  rootUser:
    password:

  db:
    user: wordpress
    password:
    name: wordpress

  replication:
    enabled: true
    user: replicator
    password:

  master:
    persistence:
      enabled: true
      storageClass: "hostpath"
      size: 2Gi
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi

  slave:
    replicas: 2
    persistence:
      enabled: true
      storageClass: "hostpath"
      size: 2Gi
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi

  metrics:
    enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
