apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - image: greegorey/load-test:1.0.0
        name: load-test
        env:
        - name: HOST
          value: wordpress:80
        - name: URI
          value: /simulate-cpu-load.php
