replicaCount: 1

image:
  repository: wordpress
  tag: latest
  # tag: 5.2.1-php7.1-fpm-alpine
  # tag: 5.2.1-php7.3-fpm
  pullPolicy: IfNotPresent

imagePullSecrets: []

livenessProbe: {}
readinessProbe: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: wordpress.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

db:
  name: wordpress
  host: mariadb:3306
  user: wordpress
  password:
  tablePrefix: wordpress

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
