apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
data:
{{ (.Files.Glob "php/*").AsConfig | indent 2 }}
