apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  dbPassword: {{ .Values.db.password | b64enc }}
